openapi: 3.0.0
info:
  version: 1.0.0
  title: 個人開発API
  description: APIの定義書
servers:
  - url: 'http://localhost:8003'
    description: Local Mock server
  - url: 'http://localhost:3000'
    description: Local API server
paths:
  /api/login:
    post:
      tags:
        - sessions
      summary: Sign In
      operationId: signIn
      requestBody:
        description: Sign In data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: SUCCESS
  /api/logout:
    delete:
      tags:
        - sessions
      summary: Sign out
      operationId: signOut
      responses:
        '204':
          description: The session was deleted successfully.
        '401':
          description: session expired error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionExpired'
  /api/registration:
    post:
      tags:
        - registration
      summary: アカウント新規登録
      description: ユーザーを新規登録する
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_profile:
                    $ref: '#/components/schemas/UserProfile'
                  login_informaiton:
                    $ref: '#/components/schemas/Login'
  '/api/mypage/{user_id}':
    get:
      tags:
        - mypage
      summary: マイページの情報を取得
      description: マイページの情報を取得する
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    put:
      tags:
        - mypage
      summary: マイページの情報を更新
      description: マイページの情報を更新する
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    delete:
      tags:
        - mypage
      summary: アカウント削除
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '204':
          description: The session was deleted successfully.
        '401':
          description: session expired error
  /api/search:
    get:
      tags:
        - search
      summary: マッチング度が高いユーザー一覧ページ取得
      description: マッチング度が高いユーザー一覧ページ
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  '/api/user_profile/{user_id}':
    get:
      tags:
        - user_detail
      summary: ユーザー詳細ページ取得
      description: ユーザーの詳細情報を取得する
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  '/api/like/{user_id}':
    get:
      tags:
        - like
      summary: 自分がいいねした人の一覧情報を取得
      description: ユーザーの詳細情報を取得する
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    post:
      tags:
        - like
      summary: ユーザーにいいねを押す
      description: ユーザーにいいねを押す
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    put:
      tags:
        - like
      summary: ユーザーいいいねを返す
      description: いいねを返す
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  '/api/like_from/{user_id}':
    get:
      tags:
        - like_from
      summary: ユーザーからのいいね一覧ページ取得
      description: ユーザーからのいいね一覧ページ取得
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  '/api/matching/{user_id}':
    get:
      tags:
        - matching
      summary: マッチングしたユーザー一覧を取得
      description: マッチングしたユーザー一覧を取得する
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  '/api/chat_room/{chat_room_id}':
    get:
      tags:
        - chat_room
      summary: 特定のユーザーとのチャット画面取得
      description: チャット画面
      parameters:
        - $ref: '#/components/parameters/ChatRoomId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    post:
      tags:
        - chat_room
      summary: チャットの投稿
      description: チャットの投稿
      parameters:
        - $ref: '#/components/parameters/ChatRoomId'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
components:
  schemas:
    UserProfile:
      type: object
      properties:
        name:
          type: string
          example: ふじかわ
        age:
          type: integer
          format: int64
          example: 28
        gender:
          type: integer
          format: int64
          example: 2
        level:
          type: integer
          format: int64
          example: 28
        purpose:
          type: integer
          format: int64
          example: 2
        how_to_connect:
          type: integer
          format: int64
          example: 1
        self_introduction:
          type: string
          example: よろしくお願いします！
    Login:
      type: object
      properties:
        login_id:
          type: integer
          format: int64
          example: 1234
        login_password:
          type: integer
          format: int64
          example: password
    SessionExpired:
      type: object
      properties:
        type:
          type: string
          example: unauthorized
        title:
          type: string
          example: Session expired
        code:
          type: integer
          format: int64
          example: 401
  parameters:
    UserId:
      name: user_id
      in: path
      description: ユーザーID
      required: true
      schema:
        type: integer
        format: int64
    ChatRoomId:
      name: chat_room_id
      in: path
      description: チャットルームID
      required: true
      schema:
        type: integer
        format: int64
