openapi: 3.0.0
info:
  version: 1.0.0
  title: 個人開発API
  description: >-
    個人開発で必要なAPIを定義するぞ！
servers:
  - url: 'http://localhost:8003'
paths:
  /users:
    get:
      description: >
        Returns all users
      operationId: findUsers
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /mypage:
    get:
      tags: 
        - マイページ
      summary: 
        マイページ情報取得雨
      description:
        ログインしたユーザーの情報を取得するよ
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags: 
        - マイページ
      summary: 
        マイページ情報取得雨
      description:
        ログインしたユーザーの情報を取得するよ
      parameters:
        - name: user_id
          in: path
          description: 取得対象のユーザー ID
          required: true
          schema:
            $ref: '#/components/schemas/user_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/fujikawa'
        required: true
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: "object"
      required:
        - "name"
      properties:
        abc:
          type: array
          items:
            oneOf:
              - type: object
                properties:
                  id:
                    type: "integer"
                    format: "int64"
                    example: 100
                  name:
                    type: "string"
                    example: "Taro"
                  status:
                    type: "string"
                    description: "user status"
                    enum:
                      - "pending"
                      - "active"
                      - "inactive"
              - type: object
                properties:
                  id:
                    type: "integer"
                    format: "int64"
                    example: 200
                  name:
                    type: "string"
                    example: "Iku"
                  status:
                    type: "string"
                    description: "user status"
                    enum:
                      - "pending"
                      - "active"
                      - "inactive"
    user_id:
      description: ユーザー識別子
      type: string
      pattern: '[a-zA-Z0-9_-]+'
      maxLength: 127
      example: halhorn
      readOnly: true
    fujikawa:
      description: ユーザー
      type: object
      properties:
        user_id:
          $ref: '#/components/schemas/user_id'
        name:
          description: 氏名
          example: 信田春満
          type: string
          maxLength: 127
        mail_address:
          description: メールアドレス
          type: string
          format: email
        age:
          description: 年齢
          example: 32
          type: integer
          minimum: 0
    Error:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"