openapi: 3.0.0
info:
  version: 1.0.0
  title: 個人開発API
  description:
    APIの定義書

servers:
  - url: http://localhost:8003
    description: Local Mock server
  - url: http://localhost:3000
    description: Local API server

paths:
  $ref: "./_paths/index.yaml"

components:
  schemas:
    $ref: "./_schemas/index.yaml"
  parameters:
    $ref: "./_parameters/index.yaml"
